### PR TITLE
Fixing recommendationsForCase, adding score to search and recommendations

### PR DESCRIPTION
**Pull request by engineersamuel**
Primarily shoring up the recommendations for a case and adding a testcase for that.

Also adding score to both recommendations and search so we can sort by that in the UI.

Minor formatting and editing as well.

Version bumped so we need a new push to bower.

### CODE REVIEW

**Comment by engineersamuel** [comment]
@renujhamtani @jtrantin @vrathee @gandhikeyur Please review

**Comment by vrathee** [comment]
Reviewed!

**Comment by renujhamtani** [comment]
looks good!

**Comment by engineersamuel** [comment]
@vrathee ty, let me know once the new version is in bower.

**Comment by engineersamuel** [comment]
ohh, I see it already is, https://github.com/redhataccess/stratajs/releases, thanks again for the quick turn around!

**Comment by renujhamtani** [comment]
@engineersamuel done

**Comment by jtrantin** [comment]
Reviewed. Sorry it took a bit longer.

**Comment by gandhikeyur** [comment]
Reviewed

**Pull request merged**
