### PR TITLE
PCM-1027: Added SOLR Query search for cases

### PR DESCRIPTION
**Pull request by jtrantin**

### CODE REVIEW

**Comment by jtrantin** [comment]
@renujhamtani @vrathee Please review.

**Comment by vrathee** [comment]
@jtrantin Please increment the version in bower.json  . That helps us in getting new changes at all places using bower update.

**Comment by jtrantin** [comment]
@vrathee Version incremented

**Comment by vrathee** [comment]
Looks Good, Reviewed!

**Pull request merged**
